### ISSUE TITLE
CannotFindSequenceForTopic: Cannot find sequence for given topic: *some topic here*

### ISSUE THREAD

**Issue by stKhaDgar** [WalletConnect/WalletConnectKotlinV2#1212]
Hello WC team!

**Describe the bug**
I create a session on my Dapp using an android wallet, after which Dapp should send me a request to verify the authenticity of the wallet (the usual _sign_ method). However, it sends me the wrong **SessionRequest**, with some other topic and addresses (most likely some session I created earlier). At the same time, every subsequent login comes with the same **SessionRequest**, and I can't authorize in this way.
Is it some kind of cache, or will the incomplete request keep coming until I reject it, or what? 

By the way I don't have any sessions when I try to create a new one. When I create one, a request of some non-existent one comes up - I try to respond to it and get the following error (which is logical, because this topic doesn't exist anymore):
`CannotFindSequenceForTopic: Cannot find sequence for given topic: *some topic here*`

I think if I clear the app cache this problem will go away, as it's obviously not in Dapp - I've tried logging in on different Dapps, but it still returns the same incorrect request.
But I'm afraid that then I won't have a problem to test, and users may have it.

**SDK Version**
 - Client: Kotlin
 - Version android-core:1.23.0

**Comment by TalhaAli00** [comment]
Hello @stKhaDgar 

Can you please provide some code snippets of how you're creating the session from your dapp and how you are sending your request to the wallet? It's odd that you're getting a different `SessionRequest` from what you are proposing.

Also, since you are building a Dapp, have you had a chance to look at our [Web3Modal](https://web3modal.com/)? We also have this available for Android

CC: @kacperoak

**Comment by stKhaDgar** [comment]
Hey @TalhaAli00 !

I wanted to show you the prints from Delegate, but when trying to create a session at all I started getting a new error - I don't even get a pairing:
![image](https://github.com/WalletConnect/WalletConnectKotlinV2/assets/33667544/7c94565d-82da-464f-aed9-fdc3c3850dc4)

What should I do to fix it :?

**Comment by muratogat** [comment]
This is a known issue as discussed here https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1130 and here https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1105 , and we hoped that it was solved in the last BOM, but apparently it isn't, also looking at the [last comment](https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1130#issuecomment-1782312862) on 1130.

This is a problem on how the session request queue is handled and completely locks up any WalletConnect process unless the app is deleted and reinstalled.

There is no fix without a SDK update.

@TalhaAli00 I don't get your comment that you find it odd. This has been reported many times before.

I even delayed a release of my app waiting for 1.23.0, because I found it unacceptable to relase it under this condition. I tested and did not encounter the error, but new reports suggest it is not (at least entirely) fixed.

**Comment by stKhaDgar** [comment]
@muratogat @TalhaAli00 
So what am I supposed to do now, guys? 
Do I need to wait for a new update or are there any other possible solutions to the problem? 

Because more and more users are coming to me with this problem, and I don't know what to do.

**Comment by muratogat** [comment]
I'm not from WC. I'm also waiting for a fix and I believe it can't be fixed without a SDK update.
@jakubuid seems to ask here https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1130 for confirmation that it also happens in the last SDK. I didn't see this problem reported recently, but it is not enough proof that it is fixed. Perhaps you can confirm to him that you see it in the latest version and, if possible, with steps to reproduce.

**Comment by stKhaDgar** [comment]
@TalhaAli00 

I updated to version **1.19.0**, but the problem is still the same - `Pairing timeout error: Timed out waiting for 5000 ms`.
Did I understand correctly that the only way out of the situation is to ask all users to reinstall the application? 😟

**Comment by mahdit8** [comment]
Seems like if app previously using old version, on migration to last version this issue will exist till uninstall and fresh install. So some of our users affected as well.

**Comment by Jimyeol** [comment]
This issue is still occurring in 1.20.0.

**Comment by jakubuid** [comment]
@Jimyeol @mahdit8 Can you please provide reproduction of your issue?

**Comment by mahdit8** [comment]
@jakubuid I don't know how to reproduce it but sometime happens and have to kill the app.
I'm using last version right now:
```
    implementation(platform("com.walletconnect:android-bom:1.21.0"))
    implementation("com.walletconnect:android-core")
    implementation("com.walletconnect:web3wallet")
```

**Comment by mahdit8** [comment]
@jakubuid Now I can add more information.
I observed that this happens on extends sessions for me with last version:
```
Web3Wallet.extendSession(extend, { success ->
                       //
                    }) { error -> // I'm getting this issue here
```
                    
```
    implementation(platform("com.walletconnect:android-bom:1.22.2"))
    implementation("com.walletconnect:android-core")
    implementation("com.walletconnect:web3wallet")
```

**Comment by jakubuid** [comment]
That's very helpful @mahdit8.
So the issue most likely happens because SDK might expire the given session before you call extend. I suggest checking the expiry of a given session before calling an extend method, to avoid having this error

**Comment by Jimyeol** [comment]
> That's very helpful @mahdit8. So the issue most likely happens because SDK might expire the given session before you call extend. I suggest checking the expiry of a given session before calling an extend method, to avoid having this error

What is the method to check if a given session has expired
